---
- name: Install Rsyslog package
  become: true
  ansible.builtin.package:
    name: rsyslog
    state: present
  notify: Enable Rsyslog
- name: Copy config
  become: true
  ansible.builtin.template:
    src: rsyslog.conf.j2
    dest: /etc/rsyslog.d/rsyslog.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart Rsyslog
