---
- name: Restart Uptime Kuma
  become: true
  become_user: "{{ uptime_kuma_user }}"
  ansible.builtin.systemd_service:
    name: uptime-kuma
    scope: user
    daemon_reload: true
    state: restarted
