---
prometheus_user: "grafana"
prometheus_packages:
  - podman
  - systemd-container
prometheus_port: "9100"
prometheus_systemd_port: "9558"
prometheus_home_hosts:
  - mediapi
  - logs
  - graphs
  - dns01
  - dns02
  - freeipa
  - files
  - semaphore
  - uptime
  - openbao
  - wazuh
  - netboot
  - netbox
  - services
  - hosted
prometheus_mbc_hosts:
  - arch.internal
prometheus_fw_hosts:
  - opnsense
