---
- name: Restart Prometheus
  become: true
  become_user: "{{ prometheus_user }}"
  ansible.builtin.systemd_service:
    name: prometheus
    scope: user
    daemon_reload: true
    state: restarted
