postfix_packages:
  - postfix
  - s-nail
  - cyrus-sasl-plain
postfix_config: "/etc/postfix/main.cf"
postfix_server_smtp: "mail.sleepycow.fun"
postfix_user: "cohenma"
postfix_server_port: 465
postfix_server_password: "{{ vault_postfix_server_password }}"
postfix_password_file: "/etc/postfix/sasl_passwd"
