---
ca_client_smallstep_url: "https://packages.smallstep.com/stable/fedora/"
ca_client_smallstep_gpg: "https://packages.smallstep.com/keys/smallstep-0x889B19391F774443.gpg"
ca_client_smallstep_deb_gpg: "https://packages.smallstep.com/keys/apt/repo-signing-key.gpg"
ca_client_url: "https://ca.localdomain:8443"
ca_client_fingerprint: "{{ vault_ca_fingerprint }}"
ca_client_root_ca: "/root/.step/certs/root_ca.crt"
ca_client_ports:
  - http
  - https
ca_client_packages:
  - step-cli
