---
tailscale_apt_keyring_path: /usr/share/keyrings/tailscale-archive-keyring.gpg
tailscale_apt_deb: deb [signed-by={{ tailscale_apt_keyring_path }}] https://pkgs.tailscale.com/{{ release_stability | lower }}/{{ tailscale_debian_distro[ansible_facts["distribution"] | lower] }} {{ apt_codename | lower }} main
