---
- name: Populate service facts
  ansible.builtin.service_facts:

- name: Install NSS
  become: true
  ansible.builtin.dnf:
    name: nss-tools
    state: present

- name: Open HTTP/HTTPS Firewalld services
  become: true
  ansible.posix.firewalld:
    service: "{{ item }}"
    permanent: true
    immediate: true
    state: enabled
  loop: "{{ caddy_ports }}"
  when: ansible_facts.services["firewalld.service"].status is defined

- name: Check for Caddy Copr reo
  ansible.builtin.stat:
    path: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:group_caddy:caddy.repo
  register: caddy_copr

- name: Install Caddy Copr repo for RHEL10
  become: true
  ansible.builtin.expect:
    command: dnf copr enable @caddy/caddy
    responses:
      "enable": "y"
  when:
    - ansible_facts["distribution_major_version"] == "10" # only needed for RHEL10, as they took out caddy from EPEL
    - not caddy_copr.stat.exists

- name: Install Caddy
  become: true
  ansible.builtin.dnf:
    name: caddy
    state: present
  notify: Run Caddy trust

- name: Start and enable Caddy
  become: true
  ansible.builtin.systemd_service:
    name: caddy
    state: started
    enabled: true

- name: Copy Caddyfile
  become: true
  ansible.builtin.template:
    src: Caddyfile.j2
    dest: /etc/caddy/Caddyfile
    owner: root
    group: root
    mode: "0644"
  notify: Restart Caddy
